### ISSUE TITLE
Shift all constant values to database

### ISSUE THREAD

**Issue by himanshuvarandani** [ssgsa-us/ssgsa.us#146]
**Is your feature request related to a problem? Please describe.**
Problem is all constant values like awardees list, scholars list and others, are in the website constants folder and needs a new deployment of website for each constant value change.

**Describe the solution you'd like**
Solution is that create a new collection in firestore database and save all the constant values there. Also, we can save the images in the storage and provide the same link in constants.

**Comment by himanshuvarandani** [comment]
@pnijhara @roshnet  Need your review on this issue

**Comment by roshnet** [comment]
@himanshuvarandani Sounds good to me.
